"""Capture docs/demo.gif from a real Brave-rendered curIAtor gallery.

This is the release replacement for the deterministic storyboard generated by
``scripts/render_demo_gif.py``. It starts a temporary one-app collection, drives the
SQLite feedback ledger through the same states the demo shows, captures browser
screenshots through Brave's DevTools protocol, and assembles a GIF.
"""
from __future__ import annotations

import argparse
import base64
import json
import os
import shutil
import socket
import struct
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError as exc:  # pragma: no cover - convenience script
    raise SystemExit("Install Pillow to capture the demo GIF: python -m pip install pillow") from exc


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "demo.gif"
W, H = 1280, 720
GIF_W, GIF_H = 1120, 630


def _free_port() -> int:
    with socket.socket() as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


def _wait_url(url: str, timeout: float = 20.0) -> None:
    deadline = time.time() + timeout
    last = None
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=1) as response:
                if response.status < 500:
                    return
        except (OSError, urllib.error.URLError) as exc:
            last = exc
        time.sleep(0.25)
    raise RuntimeError(f"timed out waiting for {url}: {last}")


def _json_get(url: str, timeout: float = 3.0):
    with urllib.request.urlopen(url, timeout=timeout) as response:
        return json.loads(response.read().decode("utf-8"))


class CdpClient:
    """Tiny enough CDP websocket client for Page.navigate and Page.captureScreenshot."""

    def __init__(self, ws_url: str):
        parsed = urllib.parse.urlparse(ws_url)
        if parsed.scheme != "ws":
            raise ValueError(f"expected ws:// URL, got {ws_url}")
        host = parsed.hostname or "127.0.0.1"
        port = parsed.port or 80
        path = parsed.path + (("?" + parsed.query) if parsed.query else "")
        self.sock = socket.create_connection((host, port), timeout=10)
        key = base64.b64encode(os.urandom(16)).decode("ascii")
        request = (
            f"GET {path} HTTP/1.1\r\n"
            f"Host: {host}:{port}\r\n"
            "Upgrade: websocket\r\n"
            "Connection: Upgrade\r\n"
            f"Sec-WebSocket-Key: {key}\r\n"
            "Sec-WebSocket-Version: 13\r\n\r\n"
        )
        self.sock.sendall(request.encode("ascii"))
        response = self.sock.recv(4096)
        if b" 101 " not in response.split(b"\r\n", 1)[0]:
            raise RuntimeError(f"websocket handshake failed: {response[:200]!r}")
        self._next_id = 0

    def close(self) -> None:
        try:
            self.sock.close()
        except OSError:
            pass

    def command(self, method: str, params: dict | None = None) -> dict:
        self._next_id += 1
        ident = self._next_id
        self._send_json({"id": ident, "method": method, "params": params or {}})
        while True:
            msg = json.loads(self._recv_message())
            if msg.get("id") == ident:
                if "error" in msg:
                    raise RuntimeError(f"CDP {method} failed: {msg['error']}")
                return msg.get("result") or {}

    def wait_expr(self, expression: str, timeout: float = 10.0) -> None:
        deadline = time.time() + timeout
        while time.time() < deadline:
            result = self.command("Runtime.evaluate", {
                "expression": expression,
                "returnByValue": True,
            })
            if (result.get("result") or {}).get("value"):
                return
            time.sleep(0.2)
        raise RuntimeError(f"timed out waiting for browser expression: {expression}")

    def navigate(self, url: str) -> None:
        self.command("Page.navigate", {"url": url})
        self.wait_expr(
            """(() => {
              const frame = document.querySelector('#app-frame');
              const doc = frame && frame.contentDocument;
              return document.readyState === 'complete' &&
                !!doc && doc.readyState === 'complete' &&
                !!doc.body && doc.body.innerText.length > 20;
            })()""",
            timeout=15,
        )
        time.sleep(0.8)

    def screenshot(self, path: Path) -> None:
        result = self.command("Page.captureScreenshot", {
            "format": "png",
            "fromSurface": True,
            "captureBeyondViewport": False,
        })
        path.write_bytes(base64.b64decode(result["data"]))

    def _send_json(self, payload: dict) -> None:
        data = json.dumps(payload, separators=(",", ":")).encode("utf-8")
        header = bytearray([0x81])
        n = len(data)
        if n < 126:
            header.append(0x80 | n)
        elif n < 65536:
            header.append(0x80 | 126)
            header.extend(struct.pack("!H", n))
        else:
            header.append(0x80 | 127)
            header.extend(struct.pack("!Q", n))
        mask = os.urandom(4)
        header.extend(mask)
        masked = bytes(b ^ mask[i % 4] for i, b in enumerate(data))
        self.sock.sendall(header + masked)

    def _recv_exact(self, n: int) -> bytes:
        chunks = []
        remaining = n
        while remaining:
            chunk = self.sock.recv(remaining)
            if not chunk:
                raise RuntimeError("websocket closed")
            chunks.append(chunk)
            remaining -= len(chunk)
        return b"".join(chunks)

    def _recv_message(self) -> str:
        chunks: list[bytes] = []
        while True:
            b1, b2 = self._recv_exact(2)
            fin = bool(b1 & 0x80)
            opcode = b1 & 0x0F
            length = b2 & 0x7F
            if length == 126:
                length = struct.unpack("!H", self._recv_exact(2))[0]
            elif length == 127:
                length = struct.unpack("!Q", self._recv_exact(8))[0]
            masked = bool(b2 & 0x80)
            mask = self._recv_exact(4) if masked else b""
            payload = self._recv_exact(length)
            if masked:
                payload = bytes(b ^ mask[i % 4] for i, b in enumerate(payload))
            if opcode == 8:
                raise RuntimeError("websocket closed")
            if opcode in (1, 2, 0):
                chunks.append(payload)
                if fin:
                    return b"".join(chunks).decode("utf-8")


def _fixed_aviato_source(source: str) -> str:
    before = """        # FLAW 1: no xaxis_title / yaxis_title
        # FLAW 2: legend dumped inside the plot, over the bars
        legend=dict(x=0.4, y=0.9, bgcolor="rgba(255,255,255,0.4)"),
        # FLAW 3: cramped margins
        margin=dict(l=8, r=8, t=30, b=8),"""
    after = """        xaxis_title="Month",
        yaxis_title="Amount ($k)",
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.08,
            xanchor="right",
            x=1.0,
            bgcolor="rgba(255,255,255,0.9)",
        ),
        margin=dict(l=72, r=36, t=82, b=62),"""
    if before not in source:
        raise RuntimeError("demo source no longer matches the planted Aviato flaws")
    return source.replace(before, after)


def _write_collection(root: Path, port: int) -> Path:
    apps = root / "apps"
    feedback = root / "feedback" / "shots"
    apps.mkdir(parents=True)
    feedback.mkdir(parents=True)
    shutil.copyfile(ROOT / "examples" / "dash" / "aviato.py", apps / "aviato.py")
    gallery = root / "gallery.yaml"
    gallery.write_text(
        f"""apps:
  - name: aviato
    title: Aviato (revenue)
    mount: {{ kind: dash-inproc, module: aviato }}
    source: apps/aviato.py
    tags: [demo, broken]
    color: "#e07b2a"
agent:
  adapter: command
  autonomy: auto-small
runner:
  mode: pinned
feedback:
  dir: feedback
  screenshots: true
auth:
  mode: none
  default_user: adam@local
git:
  commit: false
shell:
  port: {port}
  poll_seconds: 0.4
tags:
  demo: "#888"
  broken: "#e07b2a"
""",
        encoding="utf-8",
    )
    return gallery


def _start_shell(gallery: Path) -> subprocess.Popen:
    env = os.environ.copy()
    env.pop("CURIATOR_GALLERY", None)
    return subprocess.Popen(
        [sys.executable, "-m", "curiator.cli", "--gallery", str(gallery), "up"],
        cwd=ROOT,
        env=env,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.STDOUT,
    )


def _start_brave(brave_bin: str, profile: Path, debug_port: int,
                 extra_args: list[str] | None = None) -> subprocess.Popen:
    return subprocess.Popen(
        [
            brave_bin,
            "--headless=new",
            f"--remote-debugging-port={debug_port}",
            "--remote-debugging-address=127.0.0.1",
            "--disable-gpu",
            "--no-sandbox",
            "--no-first-run",
            "--no-default-browser-check",
            "--hide-scrollbars",
            f"--user-data-dir={profile}",
            f"--window-size={W},{H}",
            *(extra_args or []),
            "about:blank",
        ],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def _cdp_client(debug_port: int) -> CdpClient:
    version_url = f"http://127.0.0.1:{debug_port}/json/version"
    _wait_url(version_url)
    pages = _json_get(f"http://127.0.0.1:{debug_port}/json/list")
    page = next((p for p in pages if p.get("type") == "page"), None)
    if not page:
        raise RuntimeError("Brave did not expose a page target")
    cdp = CdpClient(page["webSocketDebuggerUrl"])
    cdp.command("Page.enable")
    cdp.command("Runtime.enable")
    cdp.command("Emulation.setDeviceMetricsOverride", {
        "width": W,
        "height": H,
        "deviceScaleFactor": 1,
        "mobile": False,
    })
    return cdp


def _seed_feedback(collection: Path, screenshot_name: str) -> None:
    from curiator import ledger
    from curiator.config import load_config_at

    cfg = load_config_at(collection / "gallery.yaml")
    ledger.save_entry(
        cfg,
        "aviato",
        entry_id="demo0001",
        stars=5,
        comment="axis labels missing, legend covers the chart, clean up the layout",
        screenshot=f"shots/{screenshot_name}",
        ts="2026-07-02T17:00:00+00:00",
        user={"id": "adam@local", "email": "adam@local", "name": "Adam", "groups": []},
    )


def _set_working(collection: Path) -> None:
    from curiator import ledger
    from curiator.config import load_config_at

    cfg = load_config_at(collection / "gallery.yaml")
    ledger.set_status(cfg, "aviato", ["demo0001"], "working")


def _set_done(collection: Path, port: int) -> None:
    from curiator import ledger
    from curiator.config import load_config_at

    app = collection / "apps" / "aviato.py"
    app.write_text(_fixed_aviato_source(app.read_text(encoding="utf-8")), encoding="utf-8")
    with urllib.request.urlopen(f"http://127.0.0.1:{port}/reload/aviato", timeout=3):
        pass
    cfg = load_config_at(collection / "gallery.yaml")
    ledger.set_status(cfg, "aviato", ["demo0001"], "done")
    ledger.add_system_note(
        cfg,
        "aviato",
        "Added Month and Amount ($k) axis titles, moved the legend above the chart, and widened the margins. Smoke-tested the Dash app import path.",
        reply_to=["demo0001"],
        status="done",
        ts="2026-07-02T17:00:12+00:00",
        agent="Codex",
    )


def _font(size: int, bold: bool = False):
    candidates = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/dejavu/DejaVuSans-Bold.ttf" if bold else "/usr/share/fonts/dejavu/DejaVuSans.ttf",
    ]
    for candidate in candidates:
        if Path(candidate).exists():
            return ImageFont.truetype(candidate, size)
    return ImageFont.load_default()


def _prepare_frame(path: Path, caption: str) -> Image.Image:
    img = Image.open(path).convert("RGB").resize((GIF_W, GIF_H), Image.Resampling.LANCZOS)
    draw = ImageDraw.Draw(img)
    font = _font(18, bold=True)
    small = _font(13)
    pad = 18
    box = (pad, GIF_H - 68, GIF_W - pad, GIF_H - 18)
    draw.rounded_rectangle(box, radius=10, fill="#20172b", outline="#20172b")
    draw.text((box[0] + 18, box[1] + 10), caption, font=font, fill="white")
    draw.text((box[2] - 252, box[1] + 15), "real Brave browser capture", font=small, fill="#cab8db")
    return img


def capture_demo(out: Path, brave_bin: str) -> None:
    with tempfile.TemporaryDirectory(prefix="curiator-demo-capture-") as tmpdir:
        tmp = Path(tmpdir)
        collection = tmp / "collection"
        port = _free_port()
        debug_port = _free_port()
        gallery = _write_collection(collection, port)
        shell = _start_shell(gallery)
        brave = None
        cdp = None
        try:
            _wait_url(f"http://127.0.0.1:{port}/api/bootstrap")
            brave = _start_brave(brave_bin, tmp / "brave-profile", debug_port)
            cdp = _cdp_client(debug_port)
            base = f"http://127.0.0.1:{port}/?app=aviato"
            shots = tmp / "shots"
            shots.mkdir()

            cdp.navigate(base)
            cdp.screenshot(shots / "01-broken.png")

            shutil.copyfile(shots / "01-broken.png", collection / "feedback" / "shots" / "aviato_demo.png")
            _seed_feedback(collection, "aviato_demo.png")
            cdp.navigate(base + "&state=new")
            cdp.screenshot(shots / "02-feedback.png")

            _set_working(collection)
            cdp.navigate(base + "&state=working")
            cdp.screenshot(shots / "03-working.png")

            _set_done(collection, port)
            cdp.navigate(base + "&state=done")
            cdp.screenshot(shots / "04-fixed.png")

            frames = [
                _prepare_frame(shots / "01-broken.png", "1. Broken app loads inside the curIAtor gallery"),
                _prepare_frame(shots / "02-feedback.png", "2. Feedback plus a captured view becomes a task"),
                _prepare_frame(shots / "03-working.png", "3. The curator starts working from that thread"),
                _prepare_frame(shots / "04-fixed.png", "4. Reply posted; refresh shows the fixed app"),
            ]
            out.parent.mkdir(parents=True, exist_ok=True)
            frames[0].save(
                out,
                save_all=True,
                append_images=frames[1:],
                duration=[1400, 1600, 1400, 2200],
                loop=0,
                optimize=True,
            )
            print(f"wrote {out.relative_to(ROOT)} ({out.stat().st_size} bytes)")
        finally:
            if cdp:
                cdp.close()
            for proc in (brave, shell):
                if proc and proc.poll() is None:
                    proc.terminate()
            for proc in (brave, shell):
                if proc:
                    try:
                        proc.wait(timeout=5)
                    except subprocess.TimeoutExpired:
                        proc.kill()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=OUT, help="GIF output path")
    parser.add_argument("--brave-bin", default=shutil.which("brave-browser") or shutil.which("brave-browser-stable"),
                        help="Brave executable")
    args = parser.parse_args(argv)
    if not args.brave_bin:
        raise SystemExit("Brave is required: install brave-browser or pass --brave-bin")
    capture_demo(args.out.resolve(), args.brave_bin)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
